import 'bootstrap-icons/font/bootstrap-icons.css';
import 'bootstrap/dist/css/bootstrap.css';
import 'glightbox/dist/css/glightbox.css';

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from './component/TopBar';
import Header from './component/Header';
import BackToTopBtn from './component/BackToTopBtn';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "E-Classy Resturant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopBar/>
        <Header/>
        {children}
        <BackToTopBtn/>
      </body>
    </html>
  );
}
